name: Update README Icon Index

on:
  push:
    branches:
      - main  # sadece main branch'te çalışır
    paths:
      - 'iconset/**'
      - 'update_readme.py'

jobs:
  update-readme:
    if: ${{ !contains(github.event.head_commit.message, 'auto:') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run update script
        run: python update_readme.py
        
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md
          git commit -m "auto: updated icon index" || echo "No changes to commit"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
